//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisEstadistico.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnalizadorBDEntities : DbContext
    {
        public AnalizadorBDEntities()
            : base("name=AnalizadorBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoria> categorias { get; set; }
        public DbSet<idioma> idiomas { get; set; }
        public DbSet<palabra> palabras { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
