//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisEstadistico.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnalizadorBDEntities : DbContext
    {
        public AnalizadorBDEntities()
            : base("name=AnalizadorBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<emoji> emojis { get; set; }
        public DbSet<feelingWord> feelingWords { get; set; }
        public DbSet<idiom> idioms { get; set; }
        public DbSet<stopword> stopwords { get; set; }
        public DbSet<word> words { get; set; }
    }
}
