//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisEstadistico.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class idiom
    {
        public idiom()
        {
            this.words = new HashSet<word>();
        }
    
        public int idiomID { get; set; }
        public string idiom1 { get; set; }
    
        public virtual ICollection<word> words { get; set; }
    }
}
