//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisisEstadistico.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class palabra
    {
        public int id { get; set; }
        public string valorPalabra { get; set; }
        public int idIdioma { get; set; }
        public int idCategoria { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual idioma idioma { get; set; }
    }
}
